// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/fabioods/go-orders/internal/usecase"
)

// CreateUserUseCase is an autogenerated mock type for the CreateUserUseCase type
type CreateUserUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, input
func (_m *CreateUserUseCase) Execute(ctx context.Context, input usecase.CreateUserDTO) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateUserDTO) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreateUserUseCase creates a new instance of CreateUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateUserUseCase {
	mock := &CreateUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
