// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/fabioods/go-orders/internal/usecase"
)

// UserAvatarUseCase is an autogenerated mock type for the UserAvatarUseCase type
type UserAvatarUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, dto
func (_m *UserAvatarUseCase) Execute(ctx context.Context, dto usecase.UserAvatarDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UserAvatarDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserAvatarUseCase creates a new instance of UserAvatarUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAvatarUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAvatarUseCase {
	mock := &UserAvatarUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
