// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// UploadRepository is an autogenerated mock type for the UploadRepository type
type UploadRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, fileName
func (_m *UploadRepository) Delete(ctx context.Context, fileName string) error {
	ret := _m.Called(ctx, fileName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upload provides a mock function with given fields: ctx, file, fileName
func (_m *UploadRepository) Upload(ctx context.Context, file multipart.File, fileName string) (string, error) {
	ret := _m.Called(ctx, file, fileName)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, string) (string, error)); ok {
		return rf(ctx, file, fileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, string) string); ok {
		r0 = rf(ctx, file, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, multipart.File, string) error); ok {
		r1 = rf(ctx, file, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUploadRepository creates a new instance of UploadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadRepository {
	mock := &UploadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
